name: Test

on:
  workflow_dispatch:
    inputs:
      data:
        description: ''
        required: true
        type: string
      debug_mode:
        description: 'Enable debug mode'
        required: false
        default: false
        type: boolean
      zip_url:
        description: 'URL of zip file to download'
        required: true
        type: string
      zip_file:
        description: 'Name for downloaded zip file'
        required: true
        type: string

jobs:
  test-batch:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        batch: [0, 1, 2, 3, 4]

    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.13'

    - name: Download Zip File
      run: |
        wget ${{ inputs.zip_url }} -O ${{ inputs.zip_file }}
        unzip ${{ inputs.zip_file }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade pip
        pip install --upgrade wheel
        pip install -r requirements.txt
        pip install --upgrade pyautogui
        pip install --upgrade python-xlib

    - name: Install Tailscale
      run: |
        sudo curl -fsSL https://tailscale.com/install.sh | sh && sudo tailscale up --authkey="tskey-auth-kZW2G84zPr11CNTRL-aiBVasVFzpTRRAXPfJgWqTHD8TtburtJ"

    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt install -y google-chrome-stable

    - name: Install chromedriver
      run: |
        seleniumbase install chromedriver

    - name: Extract Domain Batch
      run: |
        # Convert comma-separated string to array
        IFS=',' read -ra DOMAINS <<< "${{ inputs.data }}"

        # Calculate batch indices (100 domains per batch)
        BATCH_SIZE=10
        START_INDEX=$(( ${{ matrix.batch }} * BATCH_SIZE ))
        END_INDEX=$(( START_INDEX + BATCH_SIZE - 1 ))

        # Extract this batch's domains
        BATCH_DOMAINS=()
        for ((i=START_INDEX; i<=END_INDEX && i<${#DOMAINS[@]}; i++)); do
          BATCH_DOMAINS+=("${DOMAINS[i]}")
        done

        # Join back to comma-separated string
        BATCH_DATA=$(IFS=','; echo "${BATCH_DOMAINS[*]}")

        echo "Processing batch ${{ matrix.batch }}: domains $START_INDEX-$END_INDEX"
        echo "Batch data: $BATCH_DATA"
        echo "batch_data=$BATCH_DATA" >> $GITHUB_ENV

    - name: Run Test
      run: |
        if [ "${{ inputs.debug_mode }}" = "true" ]; then
          python test.py --data "$BATCH_DATA" --debug
        else
          python test.py --data "$BATCH_DATA"
        fi
